version: '3.8'

services:
  api:
    build:
      context: ./portfolio-API
      dockerfile: Dockerfile
    ports:
      - "8040:8040"
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React static site served by Nginx
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27032:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-api
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8092:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
